networks:
  endless_profile_v3:

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: endless_profile_v3_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - './:/var/www/html'
    ports:
      - '5173:5173'  # Port for @Vite
    networks:
      - endless_profile_v3
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    container_name: endless_profile_v3_nginx
    restart: unless-stopped
    tty: true
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - endless_profile_v3
    depends_on:
      - php

  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    container_name: endless_profile_v3_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql/'
      - './docker/volume/dumps:/var/dumps/'
      - './docker/mysql/conf.d/custom.conf:/etc/mysql/custom.conf'
    networks:
      - endless_profile_v3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: endless_profile_v3_phpmyadmin
    ports:
      - '9090:80'
    networks:
      - endless_profile_v3
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

#  redis:
#    image: redis:7.2-alpine
#    container_name: endless_profile_v3_redis
#    volumes:
#      - './docker/volume/redis-data:/data'
#    ports:
#      - '6379:6379'
#    command: redis-server --save 60 1 --loglevel warning
#    networks:
#      - endless_profile_v3
#    restart: unless-stopped
